### ISSUE TITLE
Unresolved reference 'OVHCloudEmbeddings'

### ISSUE THREAD

**Issue by utuncel** [ovh/public-cloud-examples#78]
When running the [RAGStreamingChatbot](https://github.com/ovh/public-cloud-examples/blob/main/ai/ai-endpoints/python-langchain-chatbot/chat-bot-streaming-rag.py) from the [python-langchain-chatbot](https://github.com/ovh/public-cloud-examples/tree/main/ai/ai-endpoints/java-langchain4j-chatbot) project, for me, it can`t find the OVHCloudEmbeddings reference. 

![error](https://github.com/user-attachments/assets/cd2b79c0-c8b7-4699-82d8-83b948dd0327)

I installed all the requirements from the requirements.txt. 
I think the error is caused by a missing requirement in the requirements.txt.

**Comment by philippart-s** [comment]
Strange because the dependency is in the official langchain_community dependency : https://github.com/langchain-ai/langchain/blob/langchain-core%3D%3D0.2.37/libs/community/langchain_community/embeddings/ovhcloud.py

And this dependency is downloaded by the `langchain_community` dependency in the `requirements.txt`

Could you try to see in your venv if the dependency is downloaded as for myself?
```bash
cd venv/lib/python3.12/site-packages/langchain_community/embeddings
 ll ovh*
-rw-r--r--  1 sphilipp  staff   3.4K Jul 19 10:56 ovhcloud.py
```

On my side I'll test by cleaning all my `venv` to test if I can reproduce the problem 😉

**Comment by utuncel** [comment]
Oh, sorry, I made a mistake with my IDE. Everything is fine now!
